#!/bin/bash

##########
# IMPORTANT NOTE
# This was tested on Ubuntu 20.04 and bash shell
# For other OSes/shells, please adapt the script to match your environment
##########

##########
# Instructions
##########
# Edit the script with your account data
##
# Make this file executable with:
#   chmod +x "$HOME"/icka/cronjob
##
# Add the following to your crontab:
#   0 * * * * /usr/bin/bash "$HOME"/icka/cronjob >/dev/null 2>&1
# (this will execute this script every hour)
##
# Enjoy!
##########

##########
# IRCCloud account email
##########
theEmail="foo@example.com"

##########
# IRCCloud account password
##########
thePassword="pass1234"

##########
# File location to write the success/failure messagee?
# Only one success/failure message will be kept every time this script is executed,
# so you do not need to worry about disk space ;D
##########
theFile="$HOME/$theEmail"

##########
# Binary location (including the binary/executable name)
# By default `$HOME/go/bin/icka'
##########
theBinary="$HOME/go/bin/icka"

##########
# WARNING! HALT! STOP RIGHT THERE!
# Don't edit anything below unless you know exactly what you're doing.
# If you touch the code below and then complain the script "suddenly stopped working" I'll touch you at night.
##########
ICKA_EMAIL="$theEmail" ICKA_PASSWORD="$thePassword" "$theBinary"

if [ $? -eq 0 ]; then
	echo "$(date) - IRCCloud session kept alive." > "$theFile"
else
	echo "$(date) - IRCCloud session couldn't be kept alive!" > "$theFile"
fi
